name: simpeg-user-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  # Myst requirements
  - nodejs>=20,<21
  - mystmd
  # Notebook requirements
  - jupyter
  - nbconvert
  - SimPEG==0.20.*
  - discretize==0.10.*
  - pymatsolver
